############Lex Items Properties##########
item.358=filled_map

#Items for Flash Entities
item.10261=bow
item.10262=crossbow
item.10332=snowball
item.10344=egg
item.19999=trident
item.10267=iron_sword
item.10268=wooden_sword
item.10272=stone_sword
item.10276=diamond_sword
item.10746=netherite_axe
item.10279=diamond_axe
item.10286=golden_axe
item.10258=iron_axe
item.10275=stone_axe
item.10271=wooden_axe
item.10283=golden_sword
item.10346=fishing_rod
item.10278=netherite_sword
item.10277=mace

#Items Pickaxe Reveal Effect
item.11000=wooden_pickaxe stone_pickaxe iron_pickaxe golden_pickaxe diamond_pickaxe netherite_pickaxe

#Items for HandLight
item.13001=glowstone torch jack_o_lantern lantern campfire shroomlight lava_bucket blaze_rod
item.13002=beacon
item.13003=redstone_torch
item.13004=soul_lantern soul_campfire soul_torch
item.13005=sea_lantern
item.13006=end_rod crying_obsidian end_crystal nether_star
item.13007=sea_pickle
item.13008=conduit
item.13009=ochre_froglight
item.13010=verdant_froglight
item.13011=pearlescent_froglight
item.13012=magma_block
item.13013=copper_bulb exposed_copper_bulb weathered_copper_bulb oxidized_copper_bulb waxed_copper_bulb waxed_exposed_copper_bulb waxed_weathered_copper_bulb waxed_oxidized_copper_bulb